{
 "title": "MonthlyStats",
 "time": { "from": "now-1y", "to": "now" },
 "panels": [
  {
   "title": "Monthly Energy Import",
   "type": "barchart",
   "description": "Energy imported from grid",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "query": "from(bucket: \"gg_grid/Day_Data\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n     r._measurement == \"daySummary\" and \r\n     r._field == \"dayGridPower\")\r\n  |> window(every: 1mo)\r\n//  |> group()\r\n  |> cumulativeSum()\r\n  |> aggregateWindow(every: 1mo, fn: last)\r\n  \r\n  \r\n\r\n  \r\n"
    }
   ]
  },
  {
   "title": "Monthly Energy Exported",
   "type": "barchart",
   "description": "Energy exported to grid ",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "Inverter Power",
     "measurement": "gridPower",
     "query": "from(bucket: \"gg_grid/Day_Data\") \r\n |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n     r._measurement == \"daySummary\" and \r\n     r._field == \"toGridDayPower\")\r\n  |> window(every: 1mo)\r\n//  |> group()\r\n  |> cumulativeSum()\r\n  |> aggregateWindow(every: 1mo, fn: last)\r\n  ",
     "select": [
      [
       { "params": [ "inverterPower" ], "type": "field" }
      ]
     ]
    },
    { "target": "sun_altitude" }
   ]
  },
  {
   "title": "Inverter Monthly Energy Production",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "query": "from(bucket: \"gg_grid/Day_Data\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n     r._measurement == \"daySummary\" and \r\n     r._field == \"invertDayPower\")\r\n  |> window(every: 1mo)\r\n//  |> group()\r\n  |> cumulativeSum()\r\n  |> aggregateWindow(every: 1mo, fn: last)\r\n  \r\n  \r\n  \r\n  "
    }
   ]
  },
  {
   "title": "Home Monthly Energy Consumption",
   "type": "barchart",
   "description": "Total home monthly energy consumption",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "Inverter Power",
     "measurement": "gridPower",
     "query": "from(bucket: \"gg_grid/Day_Data\") \r\n |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n     r._measurement == \"daySummary\" and \r\n     r._field == \"homeDayPower\")\r\n  |> window(every: 1mo)\r\n//  |> group()\r\n  |> cumulativeSum()\r\n  |> aggregateWindow(every: 1mo, fn: last)\r\n  ",
     "select": [
      [
       { "params": [ "inverterPower" ], "type": "field" }
      ]
     ]
    },
    { "target": "sun_altitude" }
   ]
  },
  {
   "title": "Home Monthly Energy Consumption",
   "type": "timeseries",
   "description": "Total home monthly energy consumption",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "Inverter Power",
     "measurement": "gridPower",
     "query": "from(bucket: \"gg_grid/Day_Data\") \r\n |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n     r._measurement == \"daySummary\" and \r\n     r._field == \"homeDayPower\")\r\n  |> window(every: 1mo)\r\n//  |> group()\r\n  |> cumulativeSum()\r\n  |> aggregateWindow(every: 1mo, fn: last)\r\n  ",
     "select": [
      [
       { "params": [ "inverterPower" ], "type": "field" }
      ]
     ]
    },
    { "target": "sun_altitude" }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    { "query": "buckets()" }
   ]
  }
 ]
}