{
 "title": "Shelly",
 "time": { "from": "now/d+6h", "to": "now/d-2h" },
 "refresh": "10s",
 "panels": [
  {
   "title": "GG Home",
   "type": "agenty-flowcharting-panel",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "Grid",
     "measurement": "gridPower",
     "query": "SELECT last(\"gridPower\") FROM \"gridPower\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "gridPower" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Panels",
     "measurement": "gridPower",
     "select": [
      [
       { "params": [ "inverterPower" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "homePower",
     "measurement": "gridPower",
     "select": [
      [
       { "params": [ "homePower" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Inverter Power",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Inverter",
     "measurement": "gridPower",
     "select": [
      [
       { "params": [ "inverterPower" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Day Energy Production",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Inverter",
     "measurement": "gridPower",
     "select": [
      [
       { "params": [ "inverterDayPower" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current Home Power",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Home ",
     "measurement": "gridPower",
     "select": [
      [
       { "params": [ "homePower" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Grid Power",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Grid",
     "measurement": "gridPower",
     "select": [
      [
       { "params": [ "gridPower" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Day Grid Consumption",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "From Grid",
     "measurement": "gridTotal",
     "select": [
      [
       { "params": [ "gridDayPower" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Power Forecast",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "Actual Power",
     "measurement": "gridPower",
     "select": [
      [
       { "params": [ "inverterPower" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Forecast",
     "measurement": "forcast",
     "query": "SELECT \"power\"  * 1000  FROM \"forcast\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "WorstCase For.",
     "measurement": "forcast",
     "query": "SELECT \"power10\"  * 1000 FROM \"forcast\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "power10" ], "type": "field" },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "BestCase For.",
     "measurement": "forcast",
     "query": "SELECT \"power90\"  *1000 FROM \"forcast\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "power90" ], "type": "field" },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Home & Grid Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "Grid power",
     "measurement": "gridPower",
     "select": [
      [
       { "params": [ "gridPower" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Home power",
     "measurement": "gridPower",
     "select": [
      [
       { "params": [ "homePower" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Day Production Forecast",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "alias": "Actual",
     "measurement": "gridPower",
     "select": [
      [
       { "params": [ "inverterDayPower" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Forecast",
     "measurement": "forcast",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ " * 500" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Worst Case For.",
     "measurement": "forcast",
     "select": [
      [
       { "params": [ "power10" ], "type": "field" },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ " * 500" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Best Case For.",
     "measurement": "forcast",
     "select": [
      [
       { "params": [ "power90" ], "type": "field" },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ " * 500" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Inverter Power",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "Inverter Power",
     "measurement": "gridPower",
     "select": [
      [
       { "params": [ "inverterPower" ], "type": "field" }
      ]
     ]
    },
    { "target": "sun_altitude" }
   ]
  },
  {
   "title": "AC Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "alias": "AC Voltage",
     "measurement": "gridPower",
     "select": [
      [
       { "params": [ "acVolt" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}